name: Test code

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "tests/**"
      - "userbot/**"
      - "dev-requirements.txt"
      - "pyproject.toml"
      - "requirements.txt"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "tests/**"
      - "userbot/**"
      - "dev-requirements.txt"
      - "pyproject.toml"
      - "requirements.txt"

permissions:
  contents: read

jobs:
  test:
    name: Test code using pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install packages
        run: pip install -r dev-requirements.txt -r requirements.txt

      - name: Run tests
        run: pytest
